import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Windows portable launcher', () => {
  it('invokes npm and Playwright through the pinned portable Node runtime', async () => {
    const script = await readFile(resolve(import.meta.dirname, '../scripts/launch-windows.ps1'), 'utf8')
    const browserCheck = await readFile(resolve(import.meta.dirname, '../scripts/check-playwright-browser.cjs'), 'utf8')
    const privatePackageBuilder = await readFile(resolve(import.meta.dirname, '../scripts/build-private-windows-package.sh'), 'utf8')
    const quickPackageBuilder = await readFile(resolve(import.meta.dirname, '../scripts/build-private-windows-package-quick.sh'), 'utf8')

    expect(script).toContain("node_modules\\npm\\bin\\npm-cli.js")
    expect(script).toContain("node_modules\\@playwright\\test\\cli.js")
    expect(script).toContain('x86_64-pc-windows-msvc')
    expect(script).toContain('codex.exe')
    expect(script).toContain('$env:AUTO_TEST_CODEX_BIN = $codexExecutable')
    expect(script).toContain('$env:AUTO_TEST_AGENT_BIN = $codexExecutable')
    expect(script).toContain('$env:AUTO_TEST_AGENT_HOME = Resolve-CodexHome')
    expect(script).toContain('AUTO_TEST_CODEX_PROBE_BIN')
    expect(script).toContain('AUTO_TEST_CODEX_PROBE_TIMEOUT_SECONDS')
    expect(script).toContain('Start-CodexProbeProcess')
    expect(script).toContain('Wait-CodexProbeInvocation')
    expect(script).toContain('Stop-CodexProbeProcess')
    expect(script).toContain('Read-CodexProbeCapture')
    expect(script).toContain('ConvertTo-PowerShellLiteral')
    expect(script).toContain('Get-RequestedAgentHost')
    expect(script).toContain("if ($requestedAgentHost -eq 'codex')")
    expect(script).toContain('OMP 使用当前 Model Profile 环境变量')
    expect(script).toContain('$startInfo.RedirectStandardOutput = $false')
    expect(script).toContain('$startInfo.RedirectStandardError = $false')
    expect(script).toContain("'auto-test-codex-probes'")
    expect(script).toContain('[IO.FileShare]::ReadWrite')
    expect(script).toContain('[Text.UTF8Encoding]::new($true)')
    expect(script).toContain('[long] $captureLimitBytes = 4MB')
    expect(script).not.toContain('ReadToEndAsync()')
    expect(script).toMatch(/Wait-CodexProbeInvocation[\s\S]*?Read-CodexProbeCapture\s+\$probeInvocation\.StandardOutputPath[\s\S]*?Read-CodexProbeCapture\s+\$probeInvocation\.StandardErrorPath/)
    expect(script).toMatch(/finally[\s\S]*?Remove-Item[\s\S]*?\$probeInvocation\.CaptureDirectory/)
    expect(script).not.toContain("& $codexExecutable exec 'Reply with exactly AUTO_TEST_API_READY.'")
    expect(script).toContain("scripts\\check-playwright-browser.cjs")
    expect(script).toContain('& $script:NodeExecutable $playwrightCli install chromium')
    expect(script).toContain('if (Test-PlaywrightChromiumReady)')
    expect(script).not.toMatch(/&\s+npx\b/)
    expect(script).not.toMatch(/&\s+npm\b/)
    expect(browserCheck).toContain("chromium.launch({ headless: true })")
    expect(browserCheck).toContain('AUTO_TEST_CHROMIUM_READY')
    expect(script).toContain('Auto-Test.private-provider.json')
    expect(script).toContain("$env:AUTO_TEST_MODEL_BASE_URL")
    expect(script).toContain("$env:AUTO_TEST_MODEL_ID")
    expect(script).toContain("$DefaultModelProfileBaseUrl = 'https://api.deepseek.com'")
    expect(script).toContain("$DefaultModelProfileModel = 'deepseek-v4-flash'")
    expect(script).toContain("$DefaultModelProfileKeyEnvironment = 'DEEPSEEK_API_KEY'")
    expect(script).toContain('AUTO_TEST_MODEL_PROFILE_ID')
    expect(script).toContain('Get-ExplicitModelProfile')
    expect(script).toContain('Test-ProviderBootstrapAvailable')
    expect(script).toMatch(/\$providerMaterialAvailable = if \(\$explicitModelProfile\)/)
    expect(script).toContain('incomplete default-provider bootstrap material block')
    expect(script).toContain('Test-DefaultDeepSeekProfile')
    expect(script).toContain('Clear-LauncherRuntimeModelProfileEnvironment')
    expect(script).toContain('当前运行由 Model Profile 管理 Provider')
    expect(script).toContain('$isDefaultDeepSeekProfile = Test-DefaultDeepSeekProfile $baseUrl $model')
    expect(script).toContain('if ($isDefaultDeepSeekProfile) {')
    expect(script).toContain("[Environment]::SetEnvironmentVariable($DefaultModelProfileKeyEnvironment, $apiKey, 'Process')")
    expect(script).toMatch(/if \(\$isDefaultDeepSeekProfile\)[\s\S]*?Clear-LauncherRuntimeModelProfileEnvironment[\s\S]*?else \{[\s\S]*?Set-RuntimeModelProfileEnvironment/)
    expect(script).toContain("$reasoningEffort = if ($isDefaultDeepSeekProfile) { 'high' } else { 'xhigh' }")
    expect(script).toContain('supports_websockets = false')
    expect(script).toContain('Parse-ApiKeyOverride')
    expect(script).toContain("$argument -eq '--api-key'")
    expect(script).toContain('临时 API Key；默认 Key 不会被替换')
    expect(script).toContain('ApiKeyOverride')
    expect(script).toContain("--model-profile 不能与 Windows 默认 Provider 的 --api-key/--reconfigure-api 同时使用")
    expect(script).toContain("$Arguments[$index] -like '--agent-host=*'")
    expect(privatePackageBuilder).toContain('AUTO_TEST_CODEX_BASE_URL')
    expect(privatePackageBuilder).toContain('AUTO_TEST_CODEX_MODEL')
    expect(privatePackageBuilder).toContain('AUTO_TEST_MODEL_BASE_URL')
    expect(privatePackageBuilder).toContain('AUTO_TEST_MODEL_ID')
    expect(privatePackageBuilder).toContain('AUTO_TEST_CODEX_BASE_URL:-https://api.deepseek.com')
    expect(privatePackageBuilder).toContain('AUTO_TEST_CODEX_MODEL:-deepseek-v4-flash')
    expect(privatePackageBuilder).toContain('Auto-Test.private-provider.json')
    expect(privatePackageBuilder).toContain('read -r model_api_key || :')
    expect(quickPackageBuilder).toContain('read -r -s model_api_key || :')
    expect(quickPackageBuilder).toContain('Model API Base URL [$base_url]')
    expect(quickPackageBuilder).toContain('Model ID [$model_id]')
    expect(quickPackageBuilder).toContain('build-private-windows-package.sh')
  })
})
