import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Windows portable launcher', () => {
  it('invokes npm and Playwright through the pinned portable Node runtime', async () => {
    const script = await readFile(resolve(import.meta.dirname, '../scripts/launch-windows.ps1'), 'utf8')
    const browserCheck = await readFile(resolve(import.meta.dirname, '../scripts/check-playwright-browser.cjs'), 'utf8')
    const privatePackageBuilder = await readFile(resolve(import.meta.dirname, '../scripts/build-private-windows-package.sh'), 'utf8')
    const quickPackageBuilder = await readFile(resolve(import.meta.dirname, '../scripts/build-private-windows-package-quick.sh'), 'utf8')

    expect(script).toContain("node_modules\\npm\\bin\\npm-cli.js")
    expect(script).toContain("node_modules\\@playwright\\test\\cli.js")
    expect(script).toContain('x86_64-pc-windows-msvc')
    expect(script).toContain('codex.exe')
    expect(script).toContain('$env:AUTO_TEST_CODEX_BIN = $codexExecutable')
    expect(script).toContain('AUTO_TEST_CODEX_PROBE_BIN')
    expect(script).toContain('AUTO_TEST_CODEX_PROBE_TIMEOUT_SECONDS')
    expect(script).toContain('Start-CodexProbeProcess')
    expect(script).toContain('Wait-CodexProbeProcess')
    expect(script).toContain('Stop-CodexProbeProcess')
    expect(script).toContain('$startInfo.RedirectStandardOutput = $true')
    expect(script).toContain('$startInfo.RedirectStandardError = $true')
    expect(script).toContain('$process.StandardOutput.ReadToEndAsync()')
    expect(script).toContain('$process.StandardError.ReadToEndAsync()')
    expect(script).not.toContain("& $codexExecutable exec 'Reply with exactly AUTO_TEST_API_READY.'")
    expect(script).toContain("scripts\\check-playwright-browser.cjs")
    expect(script).toContain('& $script:NodeExecutable $playwrightCli install chromium')
    expect(script).toContain('if (Test-PlaywrightChromiumReady)')
    expect(script).not.toMatch(/&\s+npx\b/)
    expect(script).not.toMatch(/&\s+npm\b/)
    expect(browserCheck).toContain("chromium.launch({ headless: true })")
    expect(browserCheck).toContain('AUTO_TEST_CHROMIUM_READY')
    expect(script).toContain('Auto-Test.private-provider.json')
    expect(script).toContain('$baseUrl = $env:AUTO_TEST_CODEX_BASE_URL')
    expect(script).toContain('$model = $env:AUTO_TEST_CODEX_MODEL')
    expect(script).toContain('Parse-ApiKeyOverride')
    expect(script).toContain("$argument -eq '--api-key'")
    expect(script).toContain('临时 API Key；默认 Key 不会被替换')
    expect(script).toContain('ApiKeyOverride')
    expect(privatePackageBuilder).toContain('AUTO_TEST_CODEX_BASE_URL')
    expect(privatePackageBuilder).toContain('AUTO_TEST_CODEX_MODEL')
    expect(privatePackageBuilder).toContain('Auto-Test.private-provider.json')
    expect(privatePackageBuilder).toContain('read -r model_api_key || :')
    expect(quickPackageBuilder).toContain('read -r -s model_api_key || :')
    expect(quickPackageBuilder).toContain('build-private-windows-package.sh')
  })
})
