import type { WorkflowPlannerRequest } from './planner-types.js'

export function workflowPlannerPrompt(request: WorkflowPlannerRequest): string {
  return [
    'You are the planning stage of a safety-critical AI web test automation system.',
    'Return only the structured response requested by the output schema. Do not call tools or inspect the filesystem.',
    '',
    'Your plan is a DRAFT. It will be explored, validated, and explicitly approved before Runtime can execute it.',
    'Never claim approval. Never invent credentials, phone numbers, one-time codes, order IDs, internal route IDs, or test results.',
    'All sensitive values must remain secretRef bindings. Literal business identifiers are allowed only when stated in the intake or brief.',
    '',
    'Build planJson as a JSON string containing this shape:',
    '{ version:"1.0", kind:"workflow-plan-draft", workflowId, sourceSha256, targets, dataBindings, groups, policy, review }.',
    'review must be {status:"draft", sourceRefs:string[], unresolvedAmbiguities:string[]}.',
    '',
    'Runtime DSL:',
    '- target: {id, baseUrl, allowedOrigins, optional viewport}. Use only supplied URLs and their origins.',
    '- binding: {name, source:"literal"|"secret"|"generated", valueType:"scalar"|"stringList", value|secretRef|generator}.',
    '- group: {id, optional forEach:{valuesRef,itemName}, phases}. Put entity capture and later entity use in the same group.',
    '- phase: {id,title,targetId,risk:"read"|"write"|"destructive",contextMode:"shared"|"freshPhase"|"freshPerIteration",steps,assertions,recovery?,sourceRefs}.',
    '- locator action steps use target:{description,candidates,sourceRefs}; candidates are LocatorIR objects with source:"aiSuggested".',
    '- supported steps: navigate, click, fill, press, check, ensureChecked, select, solveCaptcha, reload, wait, captureTableRow, clickAlignedTableAction.',
    '- click/fill/press/check/select use target:{description,candidates,sourceRefs}. press also requires key:string using Playwright keyboard syntax such as Enter or Control+A.',
    '- supported assertions: url, locatorText, locatorState, locatorCount, entityText, tableRowCount. locatorState expected is visible, hidden, enabled, or checked.',
    '- tableRowCount supports operator:"equals"|"gt"|"gte"|"lt"|"lte". Compile statements such as "list displays orders" or "at least one row" as operator:"gte", expected:1; use equals only for an exact count oracle.',
    '- value operands contain exactly one of {literal:string} or {valueRef:string}.',
    '- A captured entity ID is referenced only as {valueRef:"entities.<entityName>.id"}; never use "<entityName>.id".',
    '- captureTableRow must match a unique current-run entity, capture an ID with idPattern, and define bounded polling.',
    '- clickAlignedTableAction must use the captured entity ID and align a data table with its separate action table.',
    '- every phase needs at least one explicit assertion. Include final zero-active-entity safety audits for destructive workflows.',
    '- After a write or destructive submit, prefer durable URL, table, entity, or form-state assertions. Do not use a transient success toast as the only phase assertion because live locator resolution may begin after the toast disappears.',
    '- per-account browser cache isolation is modeled with forEach plus freshPerIteration.',
    '- waits must be explicit deterministic milliseconds, not random.',
    '- policy.phaseTimeoutMs and policy.actionTimeoutMs must be positive integers. destructiveActions must be requireApproval.',
    '- sourceRefs are mandatory on every phase, step, assertion, and locator target. Use refs such as phase:<id>, cell:<address>, image:<id>, brief:<line> or policy:<rule>.',
    '- Every manifest phase must be represented by at least one draft phase whose sourceRefs includes phase:<manifest-phase-id>. Never omit an unsafe, ambiguous, or currently blocked test case; preserve it so Recovery Planner and Policy Gate can fail closed.',
    '- Respect source test dependencies and preconditions when ordering phases. When an earlier phase logs into a target and dependent later phases reuse that authentication, the login phase and every dependent phase must use contextMode:"shared". freshPhase is closed at phase end and cannot establish authentication for a later shared phase. Do not repeat login, captcha, or credential steps unless the source explicitly requires re-authentication.',
    '',
    'Locator guidance:',
    '- Prefer role/name, label, placeholder, testId, then exact visible text. CSS or XPath are only candidates and must be verified by exploration.',
    '- Supply multiple conservative candidates when screenshots and text support them. Do not mark candidates as manual or playwrightCli.',
    '- A candidate may be an empty array when live exploration is required; keep a precise target description.',
    '- Add a recovery contract to a write/destructive phase only when the supplied source explicitly proves whole-phase idempotency or provides a source-backed cleanup flow already required by the test.',
    '- Never invent delete, cleanup, reset, stop, rollback, retry, or other business actions solely to satisfy recovery requirements. If recovery authority or semantics are missing, omit recovery and record a concise unresolved business ambiguity so Policy Gate blocks safely.',
    '- Use recovery.strategy="retry" only when replaying the whole phase is idempotent and cannot duplicate business effects.',
    '- Otherwise use recovery.strategy="compensate" with ordered phaseIds in the same group that restore a verified clean state.',
    '- Recovery maxAttempts must be 1..3. Read phases must not declare recovery.',
    '- retry recovery is {strategy:"retry",maxAttempts,sourceRefs}. compensate recovery is {strategy:"compensate",phaseIds,maxAttempts,sourceRefs}.',
    '',
    'Planning requirements:',
    '- Treat user-defined expected outcomes as immutable test oracles.',
    '- Add an ambiguity instead of guessing any missing business prerequisite or oracle.',
    '- Locator uncertainty, live UI text, and auth adapter expiry are exploration/preflight checks, not unresolved business ambiguities.',
    '- Authentication may be provided later through storageState/sessionStorage adapters; do not insert plaintext login data.',
    '- Use solveCaptcha for an explicitly required dynamic graphical captcha. OTP values supplied by the test engineer remain secret bindings.',
    '- A supplied verification-code or OTP secret is the exact runtime input, not permission to request or resend a code. Add a Send/Get/Resend Code action only when the intake or brief explicitly requires that external action; visible UI text alone is not evidence.',
    '- Do not guess the format of secret-bound values or rewrite them with Home/Delete/Backspace key sequences. If an explicit source requires a transformation that the DSL cannot represent declaratively, record an ambiguity.',
    '- Do not use a prior run order ID or click the first/latest row without unique matching evidence.',
    '- summary must briefly list the major modeling decisions, not secrets.',
    '',
    'SANITIZED WORKFLOW INTAKE:',
    JSON.stringify(request.manifest, null, 2),
    '',
    'SANITIZED USER BRIEF:',
    request.brief || '(none)',
    '',
    'The attached images are ordered exactly as imagePaths in the request. Use their intake image IDs and hashes as source evidence.',
  ].join('\n')
}

export function workflowPlannerRepairPrompt(
  request: WorkflowPlannerRequest,
  previousPlanJson: string,
  validationError: string,
): string {
  return [
    'You are the deterministic compile-repair stage for a safety-critical web test planner.',
    'Return only the structured response. Do not call tools. Preserve the prior business semantics and sourceRefs.',
    'Repair the prior semantic plan into the canonical workflow-plan-draft DSL described below.',
    '',
    `Validation error: ${validationError}`,
    '',
    'Canonical requirements:',
    '- Every step and assertion is a flat object with a stable id and kind. Never use type, authStateRef, state, durationMs, polling, capture, entityId, option, tableTarget, dataTableTarget, actionTableTarget, or actionTarget.',
    '- ensureChecked is {id,kind,target,expected:boolean,sourceRefs}. Use it for an idempotent switch precondition; do not use click when both initial checked and unchecked states must converge.',
    '- Stable IDs use only letters, numbers, Unicode letters/numbers, dot, underscore, or hyphen.',
    '- click/fill/press/check/select use target:{description,candidates,sourceRefs}. press is {id,kind:"press",target,key,sourceRefs}.',
    '- LocatorIR is exactly {strategy,value,name?,exact?,source:"aiSuggested"}. Convert exactText to strategy:text/value; role to strategy:role/value:<role>/name; placeholder and label similarly.',
    '- navigate is {id,kind:"navigate",url?,sourceRefs}. reload is {id,kind:"reload",sourceRefs}. wait is {id,kind:"wait",timeoutMs,sourceRefs}.',
    '- solveCaptcha is {id,kind:"solveCaptcha",imageTarget:{description,candidates,sourceRefs},inputTarget:{description,candidates,sourceRefs},sourceRefs}. Use it only when the source explicitly requires a dynamic image captcha; never model the captcha value as a data binding or literal.',
    '- captureTableRow is {id,kind,entityName,table:{headerLabels,bodyOffset,region?},match:[operands],exclude?:[operands],idPattern,timeoutMs,pollIntervalMs,refresh?,sourceRefs}. idPattern must contain a capture group.',
    '- clickAlignedTableAction is {id,kind,entityName,dataTable,actionTable,actionNames,sourceRefs}.',
    '- tableRowCount expected is an integer. entityText is {id,kind,entityName,field?,operator,expected,sourceRefs}; use field when the source names a table column. locatorState expected is only "visible", "hidden", "enabled", or "checked". Operators are only equals or contains.',
    '- tableRowCount is {id,kind:"tableRowCount",table:{headerLabels,bodyOffset,region?},match:[operands],exclude?:[operands],operator?:"equals"|"gt"|"gte"|"lt"|"lte",expected:<integer>,sourceRefs}. It never uses target.',
    '- After a write or destructive submit, use a durable URL, table, entity, or form-state assertion. Replace invented transient success-toast assertions with a source-backed durable postcondition already required by the case.',
    '- policy contains only phaseTimeoutMs, actionTimeoutMs, destructiveActions:"requireApproval".',
    '- Preserve canonical retry or compensate recovery objects and their sourceRefs when they are source-backed. Do not fabricate recovery or delete an unsafe phase when recovery evidence is absent.',
    '- Preserve every manifest phase using its phase:<id> sourceRef. Never repair an unsafe phase by deleting it.',
    '- Preserve dependency ordering and shared authenticated-session reuse. A login/authentication phase that establishes state for later phases must use contextMode:"shared" together with those dependent phases; freshPhase is closed immediately after that phase. Do not add duplicate login/captcha steps to a dependent phase when an earlier phase already authenticated the same shared target.',
    '- Recovery objects use strategy:"retry"|"compensate". Never put the recovery mode in a kind field.',
    '- Canonical captured entity references are {valueRef:"entities.<entityName>.id"}. Rewrite shorthand "<entityName>.id" to that form.',
    '- Remove auth storageState bindings; authentication adapters are CLI/runtime configuration, not workflow data bindings.',
    '- Use concrete table header labels supported by the screenshots. Exploration will verify them; do not use semantic tableTarget wrappers.',
    '- Do not add live-resolvable locator, route, status, auth-preflight, phone-format, or country-code questions to unresolvedAmbiguities. Keep only genuine missing business rules.',
    '- review.status remains draft.',
    '',
    'Example canonical capture and aligned action:',
    JSON.stringify({
      capture: {
        id: 'capture-order', kind: 'captureTableRow', entityName: 'order',
        table: { headerLabels: ['Order ID', 'Phone'], bodyOffset: 0, region: 'main' },
        match: [{ valueRef: 'phone' }, { literal: 'Active' }], idPattern: '\\b(\\d{16,24})\\b',
        timeoutMs: 60_000, pollIntervalMs: 5_000, refresh: { kind: 'reload' }, sourceRefs: ['phase:orders'],
      },
      action: {
        id: 'stop-order', kind: 'clickAlignedTableAction', entityName: 'order',
        dataTable: { headerLabels: ['Order ID', 'Phone'], bodyOffset: 0, region: 'main' },
        actionTable: { headerLabels: ['Operation'], bodyOffset: 0, region: 'fixedRight' },
        actionNames: ['Stop'], sourceRefs: ['phase:orders'],
      },
    }, null, 2),
    '',
    'SANITIZED INPUT CONTEXT:',
    JSON.stringify({ manifest: request.manifest, brief: request.brief, imageSha256s: request.imageSha256s }),
    '',
    'PRIOR PLAN JSON:',
    previousPlanJson,
  ].join('\n')
}

export function workflowExplorationRefinementPrompt(
  draftJson: string,
  explorationFeedback: string,
  pageEvidence: string,
): string {
  return [
    'You refine a canonical workflow-plan-draft after controlled live page exploration failed.',
    'Return only the structured response. Do not call tools. Keep review.status=draft.',
    '',
    'Hard invariants enforced after your response:',
    '- Do not change workflowId, sourceSha256, targets, dataBindings, group IDs/loops, phase IDs/order/risk/contextMode/recovery, or assertion semantics.',
    '- Assertion semantics include id, kind, operator, expected, entityName, match, and exclude. You may only improve assertion locator targets or table headers, except for the evidence-bounded locatorText rule below.',
    '- Do not weaken or remove assertions. Do not lower risk. Do not introduce plaintext secrets or prior-run entity IDs.',
    '- You may change, remove, add, or reorder browser steps when live evidence proves the prior UI assumption wrong.',
    '- A locatorText literal may be corrected only when sanitized live evidence contains the exact replacement text and it is the current UI representation of the same source-backed state. Do not use this exception for URLs, counts, entity/table outcomes, or user-defined business results.',
    '- When a locatorText expected literal remains unchanged, never keep a text value or accessible name that contradicts it. Adjust the target and, when needed, the preceding steps so the final page exposes that oracle.',
    '- Use ensureChecked with expected:true/false for idempotent switch preconditions. A plain click is only correct when the workflow intentionally toggles regardless of initial state.',
    '- If an optional filter input is absent but a later tableRowCount/captureTableRow already performs authoritative in-memory matching, remove the absent filter and its search click.',
    '- Treat a reported "Application error after step <id>" and applicationErrors in page evidence as authoritative evidence about that exact triggering step. Repair or remove that step before changing later submit controls or postcondition locators; never try to click or press through the error overlay.',
    '- Redaction tokens such as <redacted-secret> and <redacted-phone> reveal no prefix, length, or format information. Never add Home/Delete/Backspace or literal replacement steps to mutate a secret-bound fill unless an explicit intake, brief, cell, or image instruction specifies the exact transformation.',
    '- A supplied verification-code or OTP secret does not imply that Send/Get/Resend Code must be clicked. If such an action is not explicitly source-backed and it triggers validation or delivery errors, remove it and use the supplied secret at the actual submit step.',
    '- Preserve sourceRefs and canonical DSL field names. All locator candidates remain source:"aiSuggested" until Playwright validates them.',
    '- Fix the earliest reported failure and any directly dependent steps. Do not speculate about later unvisited pages.',
    '- If the current page is already authenticated because an earlier phase in the same shared target logged in, remove duplicated login/captcha steps from dependent phases instead of searching for login controls on the home page.',
    '',
    'CURRENT DRAFT JSON:',
    draftJson,
    '',
    'EXPLORATION FEEDBACK:',
    explorationFeedback,
    '',
    'SANITIZED LIVE PAGE EVIDENCE:',
    pageEvidence,
  ].join('\n')
}

export function workflowRecoveryPlanningPrompt(draftJson: string): string {
  return [
    'You are the recovery-planning stage of a safety-critical autonomous web test system.',
    'Return only the structured response. Do not call tools. Keep review.status=draft.',
    '',
    'You may only add or replace the recovery object on write/destructive phases.',
    'Do not change targets, bindings, groups, phase order, risk, contextMode, steps, assertions, sourceRefs, review, or policy.',
    'Add a recovery contract only when the current draft contains explicit source evidence for it. A write/destructive phase may remain without recovery so Policy Gate can block it safely.',
    'Use {strategy:"retry",maxAttempts:1..3,sourceRefs} only when replaying the entire phase is idempotent and cannot duplicate business effects.',
    'Otherwise use {strategy:"compensate",phaseIds:[...],maxAttempts:1..3,sourceRefs}.',
    'Compensation phaseIds must be ordered, unique, later phases in the same group. They must identify and clean current-run entities and finish with a clean-state assertion.',
    'Never invent idempotency, retry safety, cleanup authority, destructive permission, phases, or actions. If the draft does not already contain a source-backed compensation flow and the source does not explicitly prove retry safety, leave recovery absent.',
    'Do not use a first/latest row cleanup. Do not claim that a phase is idempotent merely because a click can be repeated.',
    'Use existing phase/step/assertion sourceRefs plus policy:<short-rule> refs; never invent credentials or entity IDs.',
    '',
    'CURRENT DRAFT JSON:',
    draftJson,
  ].join('\n')
}
